Port to blender4 Merged with blender4-image-export
Hubs-Foundation/hubs-blender-exporter pull request #296
Opened 2024-06-07 14:12 UTC by Spiderguy-F

Opened a new pull request, like you suggested

2024-06-11 08:13 UTC, keianhzo commented
I think this includes many commits that are already part of the main branch. Maybe you have merged the other fixes branch on this one? I'd expect this PR to only have the additional changed. Let's talk about it int he meetup.

2024-06-13 10:19 UTC, keianhzo reviewed
As talked in the meeting, we need to correctly handle the return parameters from `__gather_texture_transform_and_tex_coord` and we should be good to land.

I think probably something like this would work:
```
if bpy.app.version < (3, 2, 0):
    tex_transform, tex_coord = gltf2_blender_gather_texture_info.__gather_texture_transform_and_tex_coord(
        texture_socket, export_settings)
elif bpy.app.version >= (4, 0, 0):
    socket = gltf2_blender_search_node_tree.NodeSocket(
        texture_socket, blender_material)
    tex_transform, tex_coord = gltf2_blender_gather_texture_info.__gather_texture_transform_and_tex_coord(
        socket, export_settings)
else:
    tex_transform, tex_coord, _ = gltf2_blender_gather_texture_info.__gather_texture_transform_and_tex_coord(
        texture_socket, export_settings)
```

2024-06-18 17:38 UTC, keianhzo requested changes
Added updates as commit suggestion

2024-06-18 17:38 UTC, keianhzo commented on addons/io_hubs_addon/io/utils.py
> +        print("processing __gather_texture_transform_and_tex_coord")
```suggestion
```

2024-06-18 17:38 UTC, keianhzo commented on addons/io_hubs_addon/io/utils.py
> +        tex_transform, tex_coord = gltf2_blender_gather_texture_info.__gather_texture_transform_and_tex_coord(
```suggestion
        tex_transform, tex_coord, _ = gltf2_blender_gather_texture_info.__gather_texture_transform_and_tex_coord(
        texture_socket, export_settings)
```

2024-06-19 04:49 UTC, Exairnous requested changes
@keianhzo 4.0 support turned out to be trickier than we thought at the dev meetup.

@Spiderguy-F We identified at the meetup that Blender 4.0 was the cause of the errors I had been seeing.  I have added suggestions to fix all the errors and so now the add-on should work for all the supported Blender versions.  I have incorporated the fixes suggested by @keianhzo in my suggestions.  It turns out that Blender 4.0 requires the same code path as versions below 3.2, but I don't see a cleaner way to implement this than what I've suggested here; however, anyone is welcome to try to improve on my suggestions. :)

2024-06-19 04:49 UTC, Exairnous commented on addons/io_hubs_addon/io/utils.py
> +            if bpy.app.version < (4, 0, 0):
```suggestion
            if bpy.app.version < (4, 1, 0):
```

2024-06-19 04:49 UTC, Exairnous commented on addons/io_hubs_addon/io/utils.py
> +            socket, export_settings)
```suggestion
    elif bpy.app.version < (4, 0, 0):
        tex_transform, tex_coord, _ = gltf2_blender_gather_texture_info.__gather_texture_transform_and_tex_coord(
            texture_socket, export_settings)
    elif bpy.app.version < (4, 1, 0):
        tex_transform, tex_coord = gltf2_blender_gather_texture_info.__gather_texture_transform_and_tex_coord(
            texture_socket, export_settings)
```

2024-06-19 04:49 UTC, Exairnous commented on addons/io_hubs_addon/io/utils.py
>              texture_socket, export_settings)
```suggestion
        socket = gltf2_blender_search_node_tree.NodeSocket(texture_socket, blender_material)
        tex_transform, tex_coord = gltf2_blender_gather_texture_info.__gather_texture_transform_and_tex_coord(
            socket, export_settings)

```

2024-07-09 10:07 UTC, Exairnous requested changes
Left a couple slight changes for 4.0 support, but otherwise it looks good to me.

2024-07-09 10:07 UTC, Exairnous commented on addons/io_hubs_addon/io/utils.py
> +if bpy.app.version >= (4, 0, 0):
```suggestion
if bpy.app.version >= (4, 1, 0):
```

2024-07-09 10:07 UTC, Exairnous commented on addons/io_hubs_addon/io/utils.py
> +    socket = lightmap_node.inputs.get("Lightmap") if bpy.app.version < (4, 0, 0) \
```suggestion
    socket = lightmap_node.inputs.get("Lightmap") if bpy.app.version < (4, 1, 0) \
```

2024-07-16 07:50 UTC, Exairnous approved these changes
LGTM.  Merging.

2024-07-16 07:50 UTC, merged